/******************************************************************************
 *
 * Module: Port
 *
 * File Name: Port_PBcfg.c
 *
 * Description: Post Build Configuration Source file for Port Module.
 *
 * Author: Manar Salah
 ******************************************************************************/

#include "Port.h"

/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* AUTOSAR Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
		||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
		||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
#error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
		||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
		||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
#error "The SW version of PBcfg.c does not match the expected version"
#endif

/* PB structure used with Port_Init API */
const Port_ConfigType Port_Configuration =
{
		{ {PORTA_NUM, PIN0, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_UART, DISABLE, NOT_APPLICABLE},
     	      {PORTA_NUM, PIN1, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_UART, DISABLE, NOT_APPLICABLE},
		  {PORTA_NUM, PIN1, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_SSI, DISABLE, NOT_APPLICABLE},
		  {PORTA_NUM, PIN2, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_SSI, DISABLE, NOT_APPLICABLE},
		  {PORTA_NUM, PIN3, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_SSI, DISABLE, NOT_APPLICABLE},
		  {PORTA_NUM, PIN4, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_SSI, DISABLE, NOT_APPLICABLE},
		  {PORTA_NUM, PIN5, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE},
		  {PORTA_NUM, PIN6, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE},

	      {PORTB_NUM, PIN0, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE},
		  {PORTB_NUM, PIN1, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE},
		  {PORTB_NUM, PIN2, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_I2C, DISABLE, NOT_APPLICABLE},
		  {PORTB_NUM, PIN3, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_I2C, DISABLE, NOT_APPLICABLE},
		  {PORTB_NUM, PIN4, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE},
		  {PORTB_NUM, PIN5, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE},
		  {PORTB_NUM, PIN6, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE},
		  {PORTB_NUM, PIN7, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE},

		  {PORTC_NUM, PIN0, PORT_PIN_DIRECTION_UNCHANGEABLE, PORT_PIN_MODE_UNCHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_JTAG, DISABLE, NOT_APPLICABLE},
		  {PORTC_NUM, PIN1, PORT_PIN_DIRECTION_UNCHANGEABLE, PORT_PIN_MODE_UNCHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_JTAG, DISABLE, NOT_APPLICABLE},
		  {PORTC_NUM, PIN2, PORT_PIN_DIRECTION_UNCHANGEABLE, PORT_PIN_MODE_UNCHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_JTAG, DISABLE, NOT_APPLICABLE},
		  {PORTC_NUM, PIN3, PORT_PIN_DIRECTION_UNCHANGEABLE, PORT_PIN_MODE_UNCHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_JTAG, DISABLE, NOT_APPLICABLE},
		  {PORTC_NUM, PIN4, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE},
		  {PORTC_NUM, PIN5, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE},
		  {PORTC_NUM, PIN6, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE},
		  {PORTC_NUM, PIN7, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE},

		  {PORTD_NUM, PIN0, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE},
		  {PORTD_NUM, PIN1, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE},
		  {PORTD_NUM, PIN2, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE},
		  {PORTD_NUM, PIN3, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE},
		  {PORTD_NUM, PIN4, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE},
		  {PORTD_NUM, PIN5, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE},
		  {PORTD_NUM, PIN6, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE},
		  {PORTD_NUM, PIN7, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE},
              
               	  {PORTE_NUM, PIN0, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE},
		  {PORTE_NUM, PIN1, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE},
		  {PORTE_NUM, PIN2, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE},
		  {PORTE_NUM, PIN3, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE},
		  {PORTE_NUM, PIN4, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE},
		  {PORTE_NUM, PIN5, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE},
		 
                  
                  {PORTF_NUM, PIN0, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE},
		  {PORTF_NUM, PIN1, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_OUT, PORT_PIN_MODE_DIO, DISABLE, PORT_PIN_LEVEL_LOW},
		  {PORTF_NUM, PIN2, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE},
		  {PORTF_NUM, PIN3, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_DIO, DISABLE, NOT_APPLICABLE},
		  {PORTF_NUM, PIN4, PORT_PIN_DIRECTION_CHANGEABLE, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_IN, PORT_PIN_MODE_DIO, PULL_UP, NOT_APPLICABLE}}
                

};
